name: Build Project

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore .NET dependencies
        run: |
          dotnet restore

      - name: Build .NET solution
        run: |
          dotnet build --no-restore --configuration Release

      - name: Publish each project to a single file
        run: |
          dotnet publish ./KanbanCord.Bot/KanbanCord.Bot.csproj --configuration Release --runtime linux-x64 --output ./publish/KanbanCord.Bot --single-file
          dotnet publish ./KanbanCord.Core/KanbanCord.Core.csproj --configuration Release --runtime linux-x64 --output ./publish/KanbanCord.Core --single-file
          dotnet publish ./KanbanCord.Tests/KanbanCord.Tests.csproj --configuration Release --runtime linux-x64 --output ./publish/KanbanCord.Tests --single-file

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./publish/