name: Build Project

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore .NET dependencies
        run: |
          dotnet restore

      - name: Build .NET solution
        run: |
          dotnet build --no-restore --configuration Release

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            **/bin/Release/net8.0/
            **/obj/Release/
