name: Build Solution

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_and_upload_solution:
    name: Build and Upload Solution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore .NET dependencies
        run: |
          dotnet restore

      - name: Build .NET solution
        run: |
          dotnet build --no-restore --configuration Release

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .
