name: Build and Test KanbanCord

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build_project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore .NET dependencies
        run: |
          dotnet restore

      - name: Build .NET solution
        run: |
          dotnet build --no-restore --configuration Release

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            **/bin/Release/
            **/obj/Release/

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./build-output

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --no-build --verbosity normal --output ./build-output
