name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -f ./Dockerfile -t ${{ secrets.REGISTRY_USERNAME }}/kanbancord:latest .
      - name: Push to Registry
        run: |
          docker push ${{ secrets.REGISTRY_USERNAME }}/kanbancord:latest
          docker tag ${{ secrets.REGISTRY_USERNAME }}/kanbancord:latest ${{ secrets.REGISTRY_USERNAME }}/kanbancord:${{ github.ref_name }}
          docker push ${{ secrets.REGISTRY_USERNAME }}/kanbancord:${{ github.ref_name }}
