name: Unit Test Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_project:
    name: Build Project
    uses: j4asper/KanbanCord/.github/workflows/build-project.yml@11-fix-pipelines
  
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./build-output

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --no-build --verbosity normal