name: Unit Test Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_project:
    name: Build Project
    uses: j4asper/KanbanCord/.github/workflows/build-project.yml@11-fix-pipelines
  
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./build

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run Tests
        run: |
          dotnet test ./build/KanbanCord.Tests/bin/Release/net8.0/KanbanCord.Tests.dll