name: Unit Test Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_solution:
    name: Build Solution
    uses: j4asper/KanbanCord/.github/workflows/build-solution.yml@main
  
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build_solution
    steps:
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Run Tests
        run: dotnet test
